apiVersion: v1
kind: PersistentVolume
metadata:
  name: gogs-db-pv
  namespace: gogs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/gogs/db/"
