apiVersion: v1
kind: PersistentVolume
metadata:
  name: gogs-repos-pv
  namespace: gogs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/gogs/repos/"
